export enum UserRole {
  SYSTEM_ADMIN = "SYSTEM_ADMIN",
  NATIONAL_DIRECTOR = "NATIONAL_DIRECTOR",
  PROVINCIAL_DIRECTOR = "PROVINCIAL_DIRECTOR",
  REFEREE = "REFEREE",
  TOURNAMENT_OPERATOR = "TOURNAMENT_OPERATOR",
  COMPLIANCE_OFFICER = "COMPLIANCE_OFFICER",
  SUPPORT_AGENT = "SUPPORT_AGENT",
  ATHLETE = "ATHLETE",
  ORGANIZATION_LEADER = "ORGANIZATION_LEADER"
}

export enum SyncStatus {
  PENDING = "PENDING",
  PROCESSING = "PROCESSING",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED"
}

export enum CertificateType {
  TOURNAMENT_SANCTION = "TOURNAMENT_SANCTION",
  ATHLETE_COMPLETION = "ATHLETE_COMPLETION",
  WEIGH_IN_CLEARANCE = "WEIGH_IN_CLEARANCE",
  REFEREE_LICENSE = "REFEREE_LICENSE"
}

export enum CertificateStatus {
  BLOCKED = "BLOCKED",
  PENDING = "PENDING",
  ISSUED = "ISSUED",
  FAILED = "FAILED"
}

export enum SupportTicketStatus {
  PENDING = "PENDING",
  OPEN = "OPEN",
  IN_PROGRESS = "IN_PROGRESS",
  RESOLVED = "RESOLVED",
  CLOSED = "CLOSED"
}

export enum SupportTicketPriority {
  LOW = "LOW",
  NORMAL = "NORMAL",
  HIGH = "HIGH",
  URGENT = "URGENT"
}

export enum SupportTicketCategory {
  GENERAL = "GENERAL",
  TECHNICAL = "TECHNICAL",
  ACCOUNT = "ACCOUNT",
  EVENT = "EVENT",
  DISPUTE = "DISPUTE"
}

export enum SparringInviteStatus {
  PENDING = "PENDING",
  ACCEPTED = "ACCEPTED",
  DECLINED = "DECLINED",
  CANCELLED = "CANCELLED",
  EXPIRED = "EXPIRED"
}
