export enum UserRole {
  SYSTEM_ADMIN = "SYSTEM_ADMIN",
  NATIONAL_DIRECTOR = "NATIONAL_DIRECTOR",
  PROVINCIAL_DIRECTOR = "PROVINCIAL_DIRECTOR",
  REFEREE = "REFEREE",
  TOURNAMENT_OPERATOR = "TOURNAMENT_OPERATOR",
  COMPLIANCE_OFFICER = "COMPLIANCE_OFFICER",
  SUPPORT_AGENT = "SUPPORT_AGENT",
  ATHLETE = "ATHLETE",
  ORGANIZATION_LEADER = "ORGANIZATION_LEADER"
}

export enum SyncStatus {
  PENDING = "PENDING",
  PROCESSING = "PROCESSING",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED"
}
