export enum UserRole {
  SYSTEM_ADMIN = "SYSTEM_ADMIN",
  NATIONAL_DIRECTOR = "NATIONAL_DIRECTOR",
  PROVINCIAL_DIRECTOR = "PROVINCIAL_DIRECTOR",
  REFEREE = "REFEREE",
  TOURNAMENT_OPERATOR = "TOURNAMENT_OPERATOR",
  COMPLIANCE_OFFICER = "COMPLIANCE_OFFICER",
  SUPPORT_AGENT = "SUPPORT_AGENT",
  ATHLETE = "ATHLETE",
  ORGANIZATION_LEADER = "ORGANIZATION_LEADER"
}

export enum SyncStatus {
  PENDING = "PENDING",
  PROCESSING = "PROCESSING",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED"
}

export enum CertificateType {
  TOURNAMENT_SANCTION = "TOURNAMENT_SANCTION",
  ATHLETE_COMPLETION = "ATHLETE_COMPLETION",
  WEIGH_IN_CLEARANCE = "WEIGH_IN_CLEARANCE",
  REFEREE_LICENSE = "REFEREE_LICENSE"
}

export enum CertificateStatus {
  BLOCKED = "BLOCKED",
  PENDING = "PENDING",
  ISSUED = "ISSUED",
  FAILED = "FAILED"
}
