export const securitySchemes = {
  BearerAuth: {
    type: "http",
    scheme: "bearer",
    bearerFormat: "JWT",
    description: "Enter your Bearer JWT token to access protected endpoints.",
  },
};

export const rfc7807ErrorSchema = {
  type: "object",
  properties: {
    type: {
      type: "string",
      format: "uri",
      description: "A URI reference [RFC3986] that identifies the problem type.",
      example: "https://api.armsphere.com/errors/unauthorized",
    },
    title: {
      type: "string",
      description: "A short, human-readable summary of the problem type.",
      example: "Unauthorized Access",
    },
    status: {
      type: "integer",
      description: "The HTTP status code [RFC7231] generated by the origin server.",
      example: 401,
    },
    detail: {
      type: "string",
      description: "A human-readable explanation specific to this occurrence of the problem.",
      example: "The provided authorization token is expired or invalid.",
    },
    instance: {
      type: "string",
      description: "A URI reference that identifies the specific occurrence of the problem.",
      example: "/api/v1/athletes/me",
    },
    requestId: {
      type: "string",
      description: "Unique request identifier for tracing.",
      example: "req-abc123xyz",
    },
    invalidParams: {
      type: "array",
      items: {
        type: "object",
        properties: {
          name: { type: "string" },
          reason: { type: "string" },
        },
      },
      description: "List of validation errors if the status is 400 Bad Request.",
    },
  },
};

export const paginationParams = [
  {
    name: "page",
    in: "query",
    required: false,
    schema: { type: "integer", default: 1 },
    description: "Page number to retrieve.",
  },
  {
    name: "limit",
    in: "query",
    required: false,
    schema: { type: "integer", default: 20 },
    description: "Number of records per page.",
  },
];
