import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'state_providers.dart';

final List<Map<String, dynamic>> kDefaultArmSphereRankings = [
  {
    'id': 'ath_001',
    'name': 'Noman Khan',
    'firstName': 'Noman',
    'lastName': 'Khan',
    'nickname': 'The Iron Lion',
    'rank': 1,
    'rating': 2480,
    'eloRating': 2480,
    'eloDelta': 18,
    'rankTrend': 'up',
    'rankMovement': 0,
    'wins': 34,
    'losses': 2,
    'winRate': '94.4%',
    'streak': '12W Streak',
    'weightClass': '-105kg',
    'stance': 'Right Arm (Toproll)',
    'province': 'Islamabad CT',
    'club': 'Federal Armwrestling Academy',
    'pafLicense': 'PAF-PRO-2026-001',
    'isVerified': true,
    'avatarUrl': 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=600&q=80',
    'featuredStyle': 'High Riser / Speed Toproll',
  },
  {
    'id': 'ath_002',
    'name': 'Tariq Mahmood',
    'firstName': 'Tariq',
    'lastName': 'Mahmood',
    'nickname': 'Rawalpindi Titan',
    'rank': 2,
    'rating': 2310,
    'eloRating': 2310,
    'eloDelta': 12,
    'rankTrend': 'up',
    'rankMovement': 1,
    'wins': 29,
    'losses': 4,
    'winRate': '87.8%',
    'streak': '5W Streak',
    'weightClass': '+105kg',
    'stance': 'Right Arm (Hook)',
    'province': 'Punjab',
    'club': 'Rawalpindi Power House',
    'pafLicense': 'PAF-PRO-2026-002',
    'isVerified': true,
    'avatarUrl': 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=600&q=80',
    'featuredStyle': 'Inside Deep Hook',
  },
  {
    'id': 'ath_003',
    'name': 'Usman Ali',
    'firstName': 'Usman',
    'lastName': 'Ali',
    'nickname': 'The Lahore Hammer',
    'rank': 3,
    'rating': 2240,
    'eloRating': 2240,
    'eloDelta': -4,
    'rankTrend': 'down',
    'rankMovement': -1,
    'wins': 26,
    'losses': 5,
    'winRate': '83.8%',
    'streak': '1L',
    'weightClass': '-90kg',
    'stance': 'Left Arm (Press)',
    'province': 'Punjab',
    'club': 'Lahore Armwrestling Club',
    'pafLicense': 'PAF-PRO-2026-003',
    'isVerified': true,
    'avatarUrl': 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=600&q=80',
    'featuredStyle': 'Triceps Press / Shoulder Roll',
  },
  {
    'id': 'ath_004',
    'name': 'Farhan Shah',
    'firstName': 'Farhan',
    'lastName': 'Shah',
    'nickname': 'Peshawar Panther',
    'rank': 4,
    'rating': 2180,
    'eloRating': 2180,
    'eloDelta': 16,
    'rankTrend': 'up',
    'rankMovement': 2,
    'wins': 22,
    'losses': 4,
    'winRate': '84.6%',
    'streak': '8W Streak',
    'weightClass': '-80kg',
    'stance': 'Right Arm (Toproll)',
    'province': 'Khyber Pakhtunkhwa',
    'club': 'Khyber Pullers Guild',
    'pafLicense': 'PAF-PRO-2026-004',
    'isVerified': true,
    'avatarUrl': 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=600&q=80',
    'featuredStyle': 'Low Hand Toproll',
  },
  {
    'id': 'ath_005',
    'name': 'Hamza Bilal',
    'firstName': 'Hamza',
    'lastName': 'Bilal',
    'nickname': 'Karachi Viper',
    'rank': 5,
    'rating': 2110,
    'eloRating': 2110,
    'eloDelta': 8,
    'rankTrend': 'up',
    'rankMovement': 1,
    'wins': 20,
    'losses': 6,
    'winRate': '76.9%',
    'streak': '3W Streak',
    'weightClass': '-70kg',
    'stance': 'Right Arm (Hook)',
    'province': 'Sindh',
    'club': 'Sindh Supermatch Gym',
    'pafLicense': 'PAF-PRO-2026-005',
    'isVerified': true,
    'avatarUrl': 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=600&q=80',
    'featuredStyle': 'Fast Supination Hook',
  },
  {
    'id': 'ath_006',
    'name': 'Bilal Ahmed',
    'firstName': 'Bilal',
    'lastName': 'Ahmed',
    'nickname': 'Faisalabad Anvil',
    'rank': 6,
    'rating': 2050,
    'eloRating': 2050,
    'eloDelta': 0,
    'rankTrend': 'same',
    'rankMovement': 0,
    'wins': 18,
    'losses': 7,
    'winRate': '72.0%',
    'streak': '2W Streak',
    'weightClass': '-90kg',
    'stance': 'Left Arm (Toproll)',
    'province': 'Punjab',
    'club': 'Central Punjab Arm Club',
    'pafLicense': 'PAF-PRO-2026-006',
    'isVerified': true,
    'avatarUrl': 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=600&q=80',
    'featuredStyle': 'Posting Toproll',
  },
  {
    'id': 'ath_007',
    'name': 'Shehryar Raza',
    'firstName': 'Shehryar',
    'lastName': 'Raza',
    'nickname': 'Quetta Warlock',
    'rank': 7,
    'rating': 1990,
    'eloRating': 1990,
    'eloDelta': -6,
    'rankTrend': 'down',
    'rankMovement': -2,
    'wins': 16,
    'losses': 8,
    'winRate': '66.7%',
    'streak': '2L',
    'weightClass': '-105kg',
    'stance': 'Right Arm (Press)',
    'province': 'Balochistan',
    'club': 'Quetta Iron Warriors',
    'pafLicense': 'PAF-PRO-2026-007',
    'isVerified': true,
    'avatarUrl': 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=600&q=80',
    'featuredStyle': 'Side Pressure / Flop Wrist',
  },
  {
    'id': 'ath_008',
    'name': 'Zain Ul Abideen',
    'firstName': 'Zain',
    'lastName': 'Ul Abideen',
    'nickname': 'Multan Meteor',
    'rank': 8,
    'rating': 1930,
    'eloRating': 1930,
    'eloDelta': 14,
    'rankTrend': 'up',
    'rankMovement': 3,
    'wins': 15,
    'losses': 5,
    'winRate': '75.0%',
    'streak': '4W Streak',
    'weightClass': '-80kg',
    'stance': 'Right Arm (Toproll)',
    'province': 'Punjab',
    'club': 'Sultanat Armwrestling Guild',
    'pafLicense': 'PAF-PRO-2026-008',
    'isVerified': true,
    'avatarUrl': 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=600&q=80',
    'featuredStyle': 'High Drag Toproll',
  },
];

class RankingsNotifier extends AutoDisposeAsyncNotifier<List<Map<String, dynamic>>> {
  @override
  Future<List<Map<String, dynamic>>> build() async {
    final repo = ref.watch(rankingsRepositoryProvider);
    return await repo.getLeaderboards();
  }
}

final rankingsProvider = AsyncNotifierProvider.autoDispose<RankingsNotifier, List<Map<String, dynamic>>>(() {
  return RankingsNotifier();
});

