import fs from "fs";
import path from "path";
import { openapiDefinition } from "../config/openapi/index.js";

function ensureDirectoryExists(dirPath: string) {
  if (!fs.existsSync(dirPath)) {
    fs.mkdirSync(dirPath, { recursive: true });
  }
}

function generateTypeScriptSDK() {
  const sdkDir = path.resolve(process.cwd(), "packages/sdk-typescript");
  ensureDirectoryExists(sdkDir);
  ensureDirectoryExists(path.join(sdkDir, "src"));

  // 1. Create package.json
  const packageJson = {
    name: "@armsphere/sdk-typescript",
    version: "1.0.0",
    description: "Autogenerated TypeScript client SDK for ArmSphere Professional API",
    main: "dist/index.js",
    types: "dist/index.d.ts",
    scripts: {
      build: "tsc",
    },
    dependencies: {},
    devDependencies: {
      typescript: "^5.0.0",
    },
  };
  fs.writeFileSync(path.join(sdkDir, "package.json"), JSON.stringify(packageJson, null, 2));

  // 2. Create tsconfig.json
  const tsConfig = {
    compilerOptions: {
      target: "ES2020",
      module: "CommonJS",
      declaration: true,
      outDir: "./dist",
      strict: true,
      esModuleInterop: true,
      skipLibCheck: true,
      forceConsistentCasingInFileNames: true,
    },
    include: ["src/**/*"],
  };
  fs.writeFileSync(path.join(sdkDir, "tsconfig.json"), JSON.stringify(tsConfig, null, 2));

  // 3. Generate TypeScript SDK Code
  let code = `/**
 * ArmSphere Professional Client SDK
 * AUTOMATICALLY GENERATED FROM OPENAPI DEFINITION. DO NOT EDIT DIRECTLY.
 */

export interface SdkConfig {
  baseUrl?: string;
  token?: string;
  csrfToken?: string;
}

export class ArmSphereClient {
  private baseUrl: string;
  private token?: string;
  private csrfToken?: string;

  constructor(config: SdkConfig = {}) {
    this.baseUrl = config.baseUrl || "http://localhost:3000";
    this.token = config.token;
    this.csrfToken = config.csrfToken;
  }

  setToken(token: string) {
    this.token = token;
  }

  setCsrfToken(token: string) {
    this.csrfToken = token;
  }

  private async request<T>(method: string, path: string, body?: any, params?: any): Promise<T> {
    const url = new URL(path, this.baseUrl);
    if (params) {
      Object.keys(params).forEach(key => {
        if (params[key] !== undefined) {
          url.searchParams.append(key, String(params[key]));
        }
      });
    }

    const headers: Record<string, string> = {
      "Content-Type": "application/json",
    };

    if (this.token) {
      headers["Authorization"] = \`Bearer \${this.token}\`;
    }

    if (this.csrfToken) {
      headers["x-csrf-token"] = this.csrfToken;
    }

    const response = await fetch(url.toString(), {
      method,
      headers,
      body: body ? JSON.stringify(body) : undefined,
    });

    if (!response.ok) {
      let errorData;
      try {
        errorData = await response.json();
      } catch {
        errorData = { title: "HTTP Error", detail: response.statusText, status: response.status };
      }
      throw errorData;
    }

    return response.json() as Promise<T>;
  }
`;

  // Parse paths to generate typed methods
  for (const [pathStr, pathObj] of Object.entries(openapiDefinition.paths)) {
    const cleanPath = pathStr.replace(/\{([^}]+)\}/g, "${$1}");
    for (const [method, operation] of Object.entries(pathObj as any)) {
      const op = operation as any;
      const methodName = op.summary
        ? op.summary
            .toLowerCase()
            .replace(/[^a-zA-Z0-9 ]/g, "")
            .split(" ")
            .map((w: string, i: number) => (i === 0 ? w : w.charAt(0).toUpperCase() + w.slice(1)))
            .join("")
        : `${method}${pathStr.replace(/[^a-zA-Z0-9]/g, "")}`;

      const parameters = op.parameters || [];
      const hasBody = !!op.requestBody;
      const pathParams = parameters.filter((p: any) => p.in === "path");
      const queryParams = parameters.filter((p: any) => p.in === "query");

      let methodArgs: string[] = [];
      pathParams.forEach((p: any) => {
        methodArgs.push(`${p.name}: string`);
      });

      if (hasBody) {
        methodArgs.push("body: any");
      }

      if (queryParams.length > 0) {
        methodArgs.push("queryParams?: any");
      }

      code += `
  /**
   * ${op.summary || ""}
   * ${op.description || ""}
   */
  async ${methodName}(${methodArgs.join(", ")}): Promise<any> {
    return this.request<any>(
      "${method.toUpperCase()}",
      \`${cleanPath}\`,
      ${hasBody ? "body" : "undefined"},
      ${queryParams.length > 0 ? "queryParams" : "undefined"}
    );
  }
`;
    }
  }

  code += "\n}\n";

  fs.writeFileSync(path.join(sdkDir, "src/index.ts"), code);
  console.log("TypeScript SDK Generated successfully.");
}

function generateDartSDK() {
  const sdkDir = path.resolve(process.cwd(), "packages/sdk-dart");
  ensureDirectoryExists(sdkDir);
  ensureDirectoryExists(path.join(sdkDir, "lib"));

  // 1. Create pubspec.yaml
  const pubspecYaml = `name: armsphere_sdk_dart
description: Autogenerated Dart client SDK for ArmSphere Professional API.
version: 1.0.0
homepage: https://armsphere.com

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
`;
  fs.writeFileSync(path.join(sdkDir, "pubspec.yaml"), pubspecYaml);

  // 2. Generate Dart SDK Code
  let code = `/// ArmSphere Professional Client SDK
/// AUTOMATICALLY GENERATED FROM OPENAPI DEFINITION. DO NOT EDIT DIRECTLY.

import 'dart:convert';
import 'package:http/http.dart' as http;

class ArmSphereException implements Exception {
  final String title;
  final String detail;
  final int status;
  ArmSphereException(this.title, this.detail, this.status);

  @override
  String toString() => 'ArmSphereException: [$status] $title - $detail';
}

class ArmSphereClient {
  final String baseUrl;
  String? token;
  String? csrfToken;

  ArmSphereClient({this.baseUrl = 'http://localhost:3000', this.token, this.csrfToken});

  void setToken(String newToken) {
    token = newToken;
  }

  void setCsrfToken(String newToken) {
    csrfToken = newToken;
  }

  Future<Map<String, dynamic>> _request(String method, String path, {Map<String, dynamic>? body, Map<String, dynamic>? queryParams}) async {
    var uri = Uri.parse('$baseUrl$path');
    if (queryParams != null) {
      uri = uri.replace(queryParameters: queryParams.map((key, value) => MapEntry(key, value.toString())));
    }

    final headers = {
      'Content-Type': 'application/json',
    };

    if (token != null) {
      headers['Authorization'] = 'Bearer $token';
    }

    if (csrfToken != null) {
      headers['x-csrf-token'] = csrfToken!;
    }

    http.Response response;
    final bodyStr = body != null ? jsonEncode(body) : null;

    switch (method.toUpperCase()) {
      case 'GET':
        response = await http.get(uri, headers: headers);
        break;
      case 'POST':
        response = await http.post(uri, headers: headers, body: bodyStr);
        break;
      case 'PUT':
        response = await http.put(uri, headers: headers, body: bodyStr);
        break;
      case 'PATCH':
        response = await http.patch(uri, headers: headers, body: bodyStr);
        break;
      case 'DELETE':
        response = await http.delete(uri, headers: headers, body: bodyStr);
        break;
      default:
        throw Exception('Unsupported HTTP method: $method');
    }

    if (response.statusCode >= 400) {
      try {
        final err = jsonDecode(response.body);
        throw ArmSphereException(err['title'] ?? 'HTTP Error', err['detail'] ?? '', response.statusCode);
      } catch (e) {
        if (e is ArmSphereException) rethrow;
        throw ArmSphereException('HTTP Error', response.reasonPhrase ?? '', response.statusCode);
      }
    }

    return jsonDecode(response.body) as Map<String, dynamic>;
  }
`;

  // Parse paths to generate Dart methods
  for (const [pathStr, pathObj] of Object.entries(openapiDefinition.paths)) {
    // Convert path template style: /api/v1/matches/{id} -> /api/v1/matches/$id
    const cleanPath = pathStr.replace(/\{([^}]+)\}/g, "$$$1");
    for (const [method, operation] of Object.entries(pathObj as any)) {
      const op = operation as any;
      const methodName = op.summary
        ? op.summary
            .toLowerCase()
            .replace(/[^a-zA-Z0-9 ]/g, "")
            .split(" ")
            .map((w: string, i: number) => (i === 0 ? w : w.charAt(0).toUpperCase() + w.slice(1)))
            .join("")
        : `${method}${pathStr.replace(/[^a-zA-Z0-9]/g, "")}`;

      const parameters = op.parameters || [];
      const hasBody = !!op.requestBody;
      const pathParams = parameters.filter((p: any) => p.in === "path");
      const queryParams = parameters.filter((p: any) => p.in === "query");

      let methodArgs: string[] = [];
      pathParams.forEach((p: any) => {
        methodArgs.push(`String ${p.name}`);
      });

      if (hasBody) {
        methodArgs.push("Map<String, dynamic> body");
      }

      if (queryParams.length > 0) {
        methodArgs.push("Map<String, dynamic>? queryParams");
      }

      code += `
  /// ${op.summary || ""}
  /// ${op.description || ""}
  Future<Map<String, dynamic>> ${methodName}(${methodArgs.join(", ")}) async {
    return _request(
      '${method.toUpperCase()}',
      '${cleanPath}',
      ${hasBody ? "body: body" : ""},
      ${queryParams.length > 0 ? "queryParams: queryParams" : ""},
    );
  }
`;
    }
  }

  code += "\n}\n";

  fs.writeFileSync(path.join(sdkDir, "lib/sdk_dart.dart"), code);
  console.log("Dart SDK Generated successfully.");
}

// Execute generator
try {
  generateTypeScriptSDK();
  generateDartSDK();
  console.log("SDK generation pipeline complete!");
} catch (err) {
  console.error("SDK generation failed:", err);
  process.exit(1);
}
